#!/bin/bash
set -e

echo "[system-maintenance] Post-install started"

systemctl daemon-reload
systemctl enable system-maintenance.service
systemctl enable system-maintenance.timer
systemctl start system-maintenance.timer

echo "[system-maintenance] Installed OK"
exit 0

