#!/bin/bash
set -e

# install mail subsystem
if ! command -v mail >/dev/null; then
    apt update -y
    apt install -y mailutils
fi

chmod +x /usr/local/bin/system_maintenance.sh

systemctl daemon-reload
systemctl enable system-maintenance.service
systemctl enable --now system-maintenance.timer

exit 0
