#!/bin/bash
set -e

echo "[system-maintenance] Installing..."

# Создаем лог
touch /var/log/system_maintenance.log
chmod 644 /var/log/system_maintenance.log

# Делаем скрипт исполняемым
chmod +x /usr/local/bin/system_maintenance.sh

# Обновляем systemd
systemctl daemon-reload
systemctl enable system-maintenance.service
systemctl enable --now system-maintenance.timer

echo "[system-maintenance] Done."
exit 0
